import { Hono } from "hono";
import type { AppEnv } from "./env";
import { errorHandler } from "./lib/http";
import { security } from "./middleware/security";
import { devRoutes } from "./dev/routes";
import { loadSession } from "./middleware/session";
import { authRoutes } from "./auth/routes";
import { customerRoutes } from "./reservations/customer-routes";
import { staffReservationRoutes } from "./reservations/staff-routes";

export const app = new Hono<AppEnv>().basePath("/api");
app.use("*", security);
app.use("*", loadSession);
app.onError(errorHandler);
app.notFound((c) => c.json({ error: "not_found" }, 404));
app.get("/health", (c) => c.json({ ok: true }));
app.route("/dev", devRoutes);
app.route("/", authRoutes);
app.route("/customer", customerRoutes);
app.route("/staff", staffReservationRoutes);
